Repository hyperapp/router, pull requests merged in 2018-03, with the labels that each got.

#57 Add tests coverage
  package.json
  test/index.test.js
  test/link.test.js
  test/redirect.test.js
  test/switch.test.js
Labels: TESTING

#60 Don't pass through "to" and "location" attributes from <Link> to <a>
  src/Link.js
  test/link.test.js
Labels: FIX

#59 Use of Lazy Components
  README.md
  package.json
  src/Link.js
  src/Redirect.js
  src/Route.js
  test/index.test.js
  test/link.test.js
  test/redirect.test.js
Labels: FIX

#63 Fix Switch to handle lazy components
  src/Switch.js
  test/route.test.js
  test/switch.test.js
Labels: FIX

#61 Custom Link.onclick handler
  src/Link.js
  test/link.test.js
Labels: DISCUSSION, FEATURE
